/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlineproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Ankit Bhawsar
 */
public class AddFlight extends javax.swing.JFrame {

     Connection con;
    /**
     * Creates new form AddFlight
     */
    public AddFlight() {
        initComponents();
setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
      fillJList();
    }
    
    
     void fillJList(){
                    //jScrollPane1.add(new JButton("hello"));
                    //jList1.add(new JButton("hello"));
                try{
                    Class.forName("com.mysql.jdbc.Driver");  
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3307/airline_db","root","");  

                    PreparedStatement pst1;
                    String sql1 ="SELECT * FROM location ;";
                    pst1 = con.prepareStatement(sql1);

                    ResultSet rs = pst1.executeQuery(); // without arguments
                    final DefaultListModel model = new DefaultListModel();
                    while(rs.next())  
                    {
                        model.addElement(rs.getString("city"));
                    }
                    ListOfSources.setModel(model);
                    ListOfSources.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                }
                catch(Exception e){
                    System.out.println(e);
                    
                } try{
                    Class.forName("com.mysql.jdbc.Driver");  
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3307/airline_db","root","");  

                    PreparedStatement pst1;
                    String sql1 ="SELECT * FROM location ;";
                    pst1 = con.prepareStatement(sql1);

                    ResultSet rs = pst1.executeQuery(); // without arguments
                    final DefaultListModel model = new DefaultListModel();
                    while(rs.next())  
                    {
                        model.addElement(rs.getString("city"));
                    }
                    ListOfDestinations.setModel(model);
                    ListOfDestinations.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                }
                catch(Exception e){
                    System.out.println(e);
                }
                
     }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flight_name1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        flight_no1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListOfSources = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListOfDestinations = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        airplane2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        no_e = new javax.swing.JTextField();
        no_b = new javax.swing.JTextField();
        no_f = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        price_f = new javax.swing.JTextField();
        price_b = new javax.swing.JTextField();
        price_e = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CreateFlight = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Entries = new javax.swing.JLabel();
        Entries1 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        Header = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 280, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Source");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 390, 130, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREATE FLIGHT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 160, 310, 50);

        flight_name1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(flight_name1);
        flight_name1.setBounds(480, 280, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Flight No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 230, 140, 40);

        flight_no1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(flight_no1);
        flight_no1.setBounds(480, 230, 180, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Destination");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 390, 130, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Departure");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 700, 140, 40);

        ListOfSources.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ListOfSources.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListOfSources.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ListOfSourcesInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListOfSources);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(280, 430, 180, 200);

        ListOfDestinations.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ListOfDestinations.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListOfDestinations.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ListOfDestinationsInputMethodTextChanged(evt);
            }
        });
        jScrollPane4.setViewportView(ListOfDestinations);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(480, 430, 180, 200);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HH");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(590, 660, 60, 30);

        airplane2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(airplane2);
        airplane2.setBounds(480, 330, 180, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Arrival");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(240, 760, 140, 40);

        jXDatePicker2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });
        getContentPane().add(jXDatePicker2);
        jXDatePicker2.setBounds(380, 760, 180, 40);

        jXDatePicker3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jXDatePicker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker3ActionPerformed(evt);
            }
        });
        getContentPane().add(jXDatePicker3);
        jXDatePicker3.setBounds(380, 700, 180, 40);

        no_e.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(no_e);
        no_e.setBounds(1020, 280, 140, 40);

        no_b.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(no_b);
        no_b.setBounds(1020, 230, 140, 40);

        no_f.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(no_f);
        no_f.setBounds(1020, 180, 140, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("First Class");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(880, 180, 140, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Business ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(880, 230, 140, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Economy");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(880, 280, 140, 40);

        price_f.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(price_f);
        price_f.setBounds(1170, 180, 140, 40);

        price_b.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(price_b);
        price_b.setBounds(1170, 230, 140, 40);

        price_e.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(price_e);
        price_e.setBounds(1170, 280, 140, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Prices");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1170, 140, 140, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Seats");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1020, 140, 140, 40);

        CreateFlight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CreateFlight.setText("CREATE FLIGHT");
        CreateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFlightActionPerformed(evt);
            }
        });
        getContentPane().add(CreateFlight);
        CreateFlight.setBounds(1020, 350, 250, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(580, 700, 80, 40);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(670, 700, 80, 40);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(580, 760, 80, 40);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(670, 760, 80, 40);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(800, 110, 2, 320);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MM");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(680, 660, 60, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Airplane");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 330, 140, 40);

        Entries.setBackground(new java.awt.Color(0, 51, 102));
        Entries.setFont(new java.awt.Font("SimSun", 0, 13)); // NOI18N
        Entries.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Silver.jpg")); // NOI18N
        Entries.setText("jLabel3");
        getContentPane().add(Entries);
        Entries.setBounds(800, 110, 630, 320);

        Entries1.setBackground(new java.awt.Color(0, 51, 102));
        Entries1.setFont(new java.awt.Font("SimSun", 0, 13)); // NOI18N
        Entries1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Silver.jpg")); // NOI18N
        Entries1.setText("jLabel3");
        getContentPane().add(Entries1);
        Entries1.setBounds(170, 110, 630, 730);

        HomeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeButton.setText("HOME");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton);
        HomeButton.setBounds(1720, 30, 150, 40);

        Header.setBackground(new java.awt.Color(0, 0, 102));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Header.jpg")); // NOI18N
        Header.setToolTipText("");
        Header.setRequestFocusEnabled(false);
        getContentPane().add(Header);
        Header.setBounds(0, 0, 1920, 100);

        wall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Wall12.jpg")); // NOI18N
        getContentPane().add(wall);
        wall.setBounds(1, 6, 1920, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed

        this.setVisible(false);
        new AdminHome().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ListOfSourcesInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ListOfSourcesInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListOfSourcesInputMethodTextChanged

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void ListOfDestinationsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ListOfDestinationsInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListOfDestinationsInputMethodTextChanged

    private void CreateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFlightActionPerformed
       
        String flight_no=flight_no1.getText();
        String flight_name=flight_name1.getText();
        String airplane=airplane2.getText();
        
        
        String nof1=no_f.getText();
        String nob1=no_b.getText();
        String noe1=no_e.getText();
        String pf1=price_f.getText();
        String pb1=price_b.getText();
        String pe1=price_e.getText();
        
        String selected1 = ListOfSources.getSelectedValue();
        String selected2 = ListOfDestinations.getSelectedValue();
        
        String t1_1=(String) jComboBox1.getSelectedItem();
        String t1_2=(String) jComboBox2.getSelectedItem();
        String t2_1=(String) jComboBox3.getSelectedItem();
        String t2_2=(String) jComboBox4.getSelectedItem(); 
        
        Date oDate1 = jXDatePicker3.getDate();        
        DateFormat oDateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
        String ddate = oDateFormat1.format(oDate1);
        
        Date oDate2 = jXDatePicker2.getDate();        
        DateFormat oDateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
        String adate = oDateFormat2.format(oDate2);
        
        String deptime=ddate+" "+t1_1+":"+t1_2+":00";
        String arrtime=adate+" "+t2_1+":"+t2_2+":00";
        
        Date currdate = new Date();
        int error=0;
        
        if(oDate1.before(currdate))
        {
                    JOptionPane.showMessageDialog(this,"Departure Date Can't Be before today");     
                    error=1;
        }
        if(oDate1.after(oDate2))
        {
                    JOptionPane.showMessageDialog(this,"Arrival Date Can't Be before Departure");        
                    error=1;                
        }
        
        
        if(error==0)
        {

            try{

                if(selected1.equals(selected2))
                {
                      JOptionPane.showMessageDialog(this,"Source and Destination Cannot be Same!");                    
                }
                else
                {


                      Class.forName("com.mysql.jdbc.Driver");
                      Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3307/airline_db","root","");

                      String query1="select loc_id from location where city= ?;";
                      String sid1 ;
                      String did1 ;
                      PreparedStatement pst1;
                      pst1 =con.prepareStatement(query1);
                      PreparedStatement pst2;
                      pst2 =con.prepareStatement(query1);

                      pst1.setString(1,selected1);
                      pst2.setString(1,selected2);
                      ResultSet rs1=pst1.executeQuery();
                      ResultSet rs2=pst2.executeQuery();
                      rs1.next();
                      rs2.next();
                      sid1=rs1.getString("loc_id");
                      did1=rs2.getString("loc_id");

                      String query3="select admin_name from admin where active= 1;";
                      String active_admin;
                      PreparedStatement pst3;
                      pst3 =con.prepareStatement(query3);
                      ResultSet rs3=pst3.executeQuery();
                      rs3.next();
                      active_admin=rs3.getString("admin_name");



                      String insertquery="insert into flight"
                              + "(flight_no,flight_name,airplane_name,sid,did,time1,time2,"
                              + "no_first,no_business,no_economy,price_first,price_business,price_economy,admin_name) "
                              + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?);";

                      PreparedStatement pst;
                      pst =con.prepareStatement(insertquery);

                      pst.setString(1,flight_no);
                      pst.setString(2,flight_name);
                      pst.setString(3,airplane);
                      pst.setString(4,sid1);
                      pst.setString(5,did1);

                      pst.setString(6,deptime);
                      pst.setString(7,arrtime);

                      pst.setString(8,nof1);
                      pst.setString(9,nob1);
                      pst.setString(10,noe1);
                      pst.setString(11,pf1);
                      pst.setString(12,pb1);
                      pst.setString(13,pe1);
                      pst.setString(14,active_admin);

                      pst.executeUpdate();
                      JOptionPane.showMessageDialog(this,"Added Successfully");
                      this.setVisible(false);
                      new AdminHome().setVisible(true); 
                }

           }
          catch(Exception r){
              System.out.println(r);
              JOptionPane.showMessageDialog(this,r);
          }   

        }    
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_CreateFlightActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jXDatePicker3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateFlight;
    private javax.swing.JLabel Entries;
    private javax.swing.JLabel Entries1;
    private javax.swing.JLabel Header;
    private javax.swing.JButton HomeButton;
    private javax.swing.JList<String> ListOfDestinations;
    private javax.swing.JList<String> ListOfSources;
    private javax.swing.JTextField airplane2;
    private javax.swing.JTextField flight_name1;
    private javax.swing.JTextField flight_no1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private javax.swing.JTextField no_b;
    private javax.swing.JTextField no_e;
    private javax.swing.JTextField no_f;
    private javax.swing.JTextField price_b;
    private javax.swing.JTextField price_e;
    private javax.swing.JTextField price_f;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
