/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlineproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ankit Bhawsar
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        admin = new javax.swing.JTextField();
        admin_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        adminloginbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        Entries = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 450, 210, 40);

        admin.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        getContentPane().add(admin);
        admin.setBounds(530, 450, 210, 40);

        admin_password.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        admin_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(admin_password);
        admin_password.setBounds(530, 520, 210, 40);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 520, 210, 40);

        adminloginbutton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminloginbutton.setText("Log In");
        adminloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(adminloginbutton);
        adminloginbutton.setBounds(440, 590, 160, 50);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN LOGIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 340, 370, 40);

        HomeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeButton.setText("HOME");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton);
        HomeButton.setBounds(1720, 30, 150, 40);

        Entries.setBackground(new java.awt.Color(0, 51, 102));
        Entries.setFont(new java.awt.Font("SimSun", 0, 13)); // NOI18N
        Entries.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Silver.jpg")); // NOI18N
        Entries.setText("jLabel3");
        getContentPane().add(Entries);
        Entries.setBounds(220, 270, 600, 500);

        header.setBackground(new java.awt.Color(0, 0, 102));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Header.jpg")); // NOI18N
        header.setToolTipText("");
        header.setRequestFocusEnabled(false);
        getContentPane().add(header);
        header.setBounds(0, 0, 1920, 100);

        wall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Wall1.jpg")); // NOI18N
        wall.setMaximumSize(new java.awt.Dimension(1920, 1080));
        wall.setMinimumSize(new java.awt.Dimension(1920, 1080));
        wall.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(wall);
        wall.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginbuttonActionPerformed

        String name=admin.getText();
        String pass=admin_password.getText();

        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/airline_db","root","");

            PreparedStatement pst;
            String sql="Select * from admin where admin_name=? and admin_password= ?;";
            pst =con.prepareStatement(sql);
            pst.setString(1,name);
            pst.setString(2,pass);
            ResultSet rs=pst.executeQuery();

            boolean found=false,found2=false;
            while(rs.next())
            {
                if(rs.getString("admin_name").equalsIgnoreCase(name))
                {
                    found=true;
                    if(rs.getString("admin_password").equalsIgnoreCase(pass))
                    found2=true;
                }

            }

            if(found == true && found2 == true)
            {
                JOptionPane.showMessageDialog(this,"Successfully Logged In");
                this.setVisible(false);
                
                String makedeactive="update admin set active=0";        
                PreparedStatement pst1;
                pst1 =con.prepareStatement(makedeactive);
                pst1.executeUpdate();
                
                String makeactive="update admin set active=1 where admin_name=?;";                 
                PreparedStatement pst2;
                pst2 =con.prepareStatement(makeactive);
                pst2.setString(1,name);                
                pst2.executeUpdate();
                
                new AdminHome().setVisible(true);
            }
            else if(found == false || found2 == false)
            {
                JOptionPane.showMessageDialog(this,"Incorrect Details");
            }

        }
        catch(Exception r){
            System.out.println(r);
        }
    }//GEN-LAST:event_adminloginbuttonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed

        this.setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void admin_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Entries;
    private javax.swing.JButton HomeButton;
    private javax.swing.JTextField admin;
    private javax.swing.JPasswordField admin_password;
    private javax.swing.JButton adminloginbutton;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables

    private void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
