/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlineproject;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
/**
 *
 * @author Ankit Bhawsar
 */

public final class BlockUser extends javax.swing.JFrame {

    Connection con;
    public BlockUser() throws SQLException, ClassNotFoundException {
        initComponents();
setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
      fillJList();
    }
        
        void fillJList(){
                    //jScrollPane1.add(new JButton("hello"));
                    //jList1.add(new JButton("hello"));
                try{
                    Class.forName("com.mysql.jdbc.Driver");  
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3307/airline_db","root","");  

                    PreparedStatement pst1;
                    String sql1 ="SELECT * FROM user where block_state=0;";
                    pst1 = con.prepareStatement(sql1);

                    ResultSet rs = pst1.executeQuery(); // without arguments
                    final DefaultListModel model = new DefaultListModel();
                    while(rs.next())  
                    {
                        model.addElement(rs.getString("username"));
                    }
                    ListOfUsers.setModel(model);
                    ListOfUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                }
                catch(Exception e){
                    System.out.println(e);
                }
                
                try{
                    Class.forName("com.mysql.jdbc.Driver");  
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3307/airline_db","root","");  

                    PreparedStatement pst2;
                    String sql2 ="SELECT * FROM user where block_state=1;;";
                    pst2 = con.prepareStatement(sql2);

                    ResultSet rs = pst2.executeQuery(); // without arguments
                    final DefaultListModel model = new DefaultListModel();
                    while(rs.next())  
                    {
                        model.addElement(rs.getString("username"));
                    }
                    ListOfBLockedUsers.setModel(model);
                    ListOfBLockedUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                }
                catch(Exception e){
                    System.out.println(e);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListOfBLockedUsers = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListOfUsers = new javax.swing.JList<>();
        UnblockUser = new javax.swing.JButton();
        RemoveUser = new javax.swing.JButton();
        BlockUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        Entries = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        ListOfBLockedUsers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ListOfBLockedUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListOfBLockedUsers.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ListOfBLockedUsersInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListOfBLockedUsers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 280, 220, 430);

        ListOfUsers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ListOfUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListOfUsers.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ListOfUsersInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListOfUsers);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 280, 220, 430);

        UnblockUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        UnblockUser.setText("UNBLOCK USER");
        UnblockUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnblockUserActionPerformed(evt);
            }
        });
        getContentPane().add(UnblockUser);
        UnblockUser.setBounds(550, 720, 220, 50);

        RemoveUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RemoveUser.setText("REMOVE USER");
        RemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveUser);
        RemoveUser.setBounds(440, 780, 220, 50);

        BlockUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BlockUser.setText("BLOCK USER");
        BlockUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockUserActionPerformed(evt);
            }
        });
        getContentPane().add(BlockUser);
        BlockUser.setBounds(320, 720, 220, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALL USERS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 240, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BLOCKED USERS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 240, 220, 30);

        HomeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeButton.setText("HOME");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton);
        HomeButton.setBounds(1720, 30, 150, 40);

        Entries.setBackground(new java.awt.Color(0, 51, 102));
        Entries.setFont(new java.awt.Font("SimSun", 0, 13)); // NOI18N
        Entries.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Silver.jpg")); // NOI18N
        Entries.setText("jLabel3");
        getContentPane().add(Entries);
        Entries.setBounds(250, 210, 590, 660);

        Header.setBackground(new java.awt.Color(0, 0, 102));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Header.jpg")); // NOI18N
        Header.setToolTipText("");
        Header.setRequestFocusEnabled(false);
        getContentPane().add(Header);
        Header.setBounds(0, 0, 1920, 100);

        wall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\wall17.jpg")); // NOI18N
        getContentPane().add(wall);
        wall.setBounds(1, 6, 1940, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListOfBLockedUsersInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ListOfBLockedUsersInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListOfBLockedUsersInputMethodTextChanged

    private void UnblockUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnblockUserActionPerformed
        
          String selected2 = ListOfBLockedUsers.getSelectedValue();
        try
        {
            String query = "update user set block_state=0 where username = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1,selected2);
            // execute insert SQL stetement
            preparedStatement .executeUpdate();
            
            ListOfBLockedUsers.removeAll();
            this.fillJList();
            JOptionPane.showMessageDialog(this,"User Unblocked Successfully");  
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_UnblockUserActionPerformed

    private void BlockUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockUserActionPerformed
        
          String selected1 = ListOfUsers.getSelectedValue();
        try
        {
            String query = "update user set block_state=1 where username = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1,selected1);
            // execute insert SQL stetement
            preparedStatement .executeUpdate();
            
            ListOfBLockedUsers.removeAll();
            this.fillJList();
            JOptionPane.showMessageDialog(this,"User Blocked Successfully");  
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_BlockUserActionPerformed

    private void RemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserActionPerformed
        
        String selected = ListOfUsers.getSelectedValue();
        try
        {
            String query1 = "delete from booking where username = ?";
            PreparedStatement preparedStatement1 = con.prepareStatement(query1);
            preparedStatement1.setString(1,selected);
            preparedStatement1.executeUpdate();
            
            String query = "delete from user where username = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1,selected);
            preparedStatement .executeUpdate();
            
            ListOfBLockedUsers.removeAll();
            this.fillJList();
            JOptionPane.showMessageDialog(this,"User Removed Successfully");  
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_RemoveUserActionPerformed

    private void ListOfUsersInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ListOfUsersInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListOfUsersInputMethodTextChanged

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed

        this.setVisible(false);
        new AdminHome().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlockUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlockUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlockUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlockUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BlockUser().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BlockUser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BlockUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlockUser;
    private javax.swing.JLabel Entries;
    private javax.swing.JLabel Header;
    private javax.swing.JButton HomeButton;
    private javax.swing.JList<String> ListOfBLockedUsers;
    private javax.swing.JList<String> ListOfUsers;
    private javax.swing.JButton RemoveUser;
    private javax.swing.JButton UnblockUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
