/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlineproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ankit Bhawsar
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fname1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lname1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phno1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        passno1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        password2 = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        Entries = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        Header = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE ACCOUNT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 180, 340, 50);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 260, 190, 40);

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(username);
        username.setBounds(540, 260, 210, 40);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("First Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 330, 190, 40);

        fname1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(fname1);
        fname1.setBounds(540, 330, 210, 40);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Last Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 400, 190, 40);

        lname1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lname1);
        lname1.setBounds(540, 400, 210, 40);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Email Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 470, 190, 40);

        email1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(email1);
        email1.setBounds(540, 470, 210, 40);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Address");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 540, 190, 40);

        addr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(addr);
        addr.setBounds(540, 540, 210, 40);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Phone Number");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 610, 190, 40);

        phno1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(phno1);
        phno1.setBounds(540, 610, 210, 40);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Passport Number");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 680, 190, 40);

        passno1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(passno1);
        passno1.setBounds(540, 680, 210, 40);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Create Password");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 750, 190, 40);
        getContentPane().add(password1);
        password1.setBounds(540, 750, 210, 40);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Confirm Password");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 820, 200, 40);
        getContentPane().add(password2);
        password2.setBounds(540, 820, 210, 40);

        SignUpButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpButton);
        SignUpButton.setBounds(470, 890, 160, 50);

        Entries.setBackground(new java.awt.Color(0, 51, 102));
        Entries.setFont(new java.awt.Font("SimSun", 0, 13)); // NOI18N
        Entries.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Silver.jpg")); // NOI18N
        Entries.setText("jLabel3");
        getContentPane().add(Entries);
        Entries.setBounds(250, 150, 600, 830);

        HomeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeButton.setText("HOME");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton);
        HomeButton.setBounds(1720, 30, 150, 40);

        Header.setBackground(new java.awt.Color(0, 0, 102));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\Header.jpg")); // NOI18N
        Header.setToolTipText("");
        Header.setRequestFocusEnabled(false);
        getContentPane().add(Header);
        Header.setBounds(0, 0, 1920, 100);

        wall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\AirlineProject\\Pictures\\wall16.jpg")); // NOI18N
        getContentPane().add(wall);
        wall.setBounds(1, 6, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        
        String uname=username.getText();
        String fname=fname1.getText();
        String lname=lname1.getText();
        String email=email1.getText();
        String address=addr.getText();
        String phno=phno1.getText();
        String passno=passno1.getText();
        String pass1=password1.getText();
        String pass2=password2.getText();
        
        int error=0;
        long phonenumber;
        
        if(!(  email.contains("@")  &&  email.contains(".") ))
        {
            JOptionPane.showMessageDialog(this,"Incorrect Email Address");
            error=1;
        }
        if(phno.length()>10 || phno.length()<10)
        {
            JOptionPane.showMessageDialog(this,"Incorrect Phone Number");
            error=1;
        }
        
        
        if(error==0)
        {

            phonenumber=Long.parseLong(phno);

              try{

                  if(pass1.equals(pass2))
                  {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/airline_db","root","");


                        String insertquery="insert into user(username,user_password,fname,lname,email,address,phno,passno,credits,block_state) values(?,?,?,?,?,?,?,?,0,false);";

                        PreparedStatement pst;
                        pst =con.prepareStatement(insertquery);



                        pst.setString(1,uname);
                        pst.setString(2,pass1);
                        pst.setString(3,fname);
                        pst.setString(4,lname);
                        pst.setString(5,email);
                        pst.setString(6,address);
                        pst.setString(7,phno);
                        pst.setString(8,passno);

                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Account Created Successfully");
                        this.setVisible(false);
                        new UserHome().setVisible(true);


                        String makedeactive="update user set active_user=0";        
                        PreparedStatement pst3;
                        pst3 =con.prepareStatement(makedeactive);
                        pst3.executeUpdate();

                        String makeactive="update user set active_user=1 where username=?;";                 
                        PreparedStatement pst2;
                        pst2 =con.prepareStatement(makeactive);
                        pst2.setString(1,uname);                
                        pst2.executeUpdate();

                  }
                  else
                  {
                        JOptionPane.showMessageDialog(this,"Passwords do not Match");
                  }

             }
            catch(Exception r){
                System.out.println(r);
                JOptionPane.showMessageDialog(this,r);
            }   
        }
        
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed

        this.setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Entries;
    private javax.swing.JLabel Header;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField fname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname1;
    private javax.swing.JTextField passno1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField phno1;
    private javax.swing.JTextField username;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
